version: '3.1'

services:
  influxdb:
    image: influxdb:1.7
    volumes:
    - ./storage/:/var/lib/influxdb
    ports:
    - 8086:8086
    environment:
    - INFLUXDB_HTTP_AUTH_ENABLED=false
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=admin
    - INFLUXDB_USER=user
    - INFLUXDB_USER_PASSWORD=user
